export const pantryIngredients = [
  { id: 1, name: "Flour" },
  { id: 2, name: "Sugar" },
  { id: 3, name: "Salt" },
  { id: 4, name: "Baking Powder" },
  { id: 5, name: "Eggs" },
  { id: 6, name: "Milk" },
  { id: 7, name: "Butter" },
  { id: 8, name: "Vanilla Extract" },
  { id: 9, name: "Chocolate Chips" },
  { id: 10, name: "Brown Sugar" },
  { id: 11, name: "Olive Oil" },
  { id: 12, name: "Garlic" },
  { id: 13, name: "Onion" },
  { id: 14, name: "Tomatoes" },
  { id: 15, name: "Lettuce" },
  { id: 16, name: "Cucumber" },
  { id: 17, name: "Carrots" },
  { id: 18, name: "Celery" },
  { id: 19, name: "Chicken" },
  { id: 20, name: "Beef" },
];
